apiVersion: apps/v1
kind: Deployment
metadata:
  name: flow-secrets-app
  labels:
    app: flow-secrets-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flow-secrets-app
  template:
    metadata:
      labels:
        app: flow-secrets-app
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "flowsecretsapp"
        dapr.io/app-port: "7000"
        dapr.io/log-level: "debug"
        dapr.io/config: "appconfig"
    spec:
      containers:
      - name: flowsecretsapp
        image: youracr.azurecr.io/flow-secrets:latest
        ports:
        - containerPort: 7000
        imagePullPolicy: Always